# Generated by Django 5.2 on 2025-05-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Vacina')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('recommended_age_months', models.PositiveIntegerField(verbose_name='Idade Recomendada (meses)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['recommended_age_months'],
            },
        ),
    ]
