name: Keep App Alive

# roda a cada 10 minutos em UTC
on:
    schedule:
      - cron: '*/10 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl health endpoint
        run: |
          STATUS=$(curl -o /dev/null -s -w "%{http_code}" https://vacinakids.onrender.com/health/)
          echo "Status code: $STATUS"
          if [ "$STATUS" -ne 200 ]; then
            echo "❌ Health check failed (status $STATUS)"
            exit 1
          fi